### ISSUE TITLE
Change background color 

### ISSUE THREAD

**Issue by AlizayAyesha** [Ahmadshah35/payment-form#1]
I want to change the background color of this form

**Comment by Ahmadshah35** [comment]
ok then you will change it and thanks  for approaching.

**Comment by AlizayAyesha** [comment]
![image](https://github.com/Ahmadshah35/payment-form/assets/68489612/5699ae3b-7bd1-49d1-b6c3-d63d9b8c8ea5)
 see the results is it better?
